// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrCJuo7etaEr3iNnvB48lRYDqc3qUrd8k',
    appId: '1:725840638676:web:7795ae5e3dba4540c40141',
    messagingSenderId: '725840638676',
    projectId: 'municipalidad-f8706',
    authDomain: 'municipalidad-f8706.firebaseapp.com',
    storageBucket: 'municipalidad-f8706.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATaZJpXfkTX7-F7zMCiyihOiS5NafZEMg',
    appId: '1:725840638676:android:0f762d0293585082c40141',
    messagingSenderId: '725840638676',
    projectId: 'municipalidad-f8706',
    storageBucket: 'municipalidad-f8706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TybQPldeFRxBCmWzym5LbDLXMkIEBvY',
    appId: '1:725840638676:ios:624a51d0f2d84e55c40141',
    messagingSenderId: '725840638676',
    projectId: 'municipalidad-f8706',
    storageBucket: 'municipalidad-f8706.firebasestorage.app',
    iosBundleId: 'com.example.municipalidad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrCJuo7etaEr3iNnvB48lRYDqc3qUrd8k',
    appId: '1:725840638676:web:1f22da28c68e591dc40141',
    messagingSenderId: '725840638676',
    projectId: 'municipalidad-f8706',
    authDomain: 'municipalidad-f8706.firebaseapp.com',
    storageBucket: 'municipalidad-f8706.firebasestorage.app',
  );
}
